[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["pip install -r requirements.txt --no-cache-dir"]

[start]
cmd = "python blog_project/manage.py collectstatic --noinput && python blog_project/manage.py migrate --noinput && gunicorn blog_project.wsgi:application --bind 0.0.0.0:$PORT"
